const leaderboard=document.getElementById('leaderboard'),template=document.getElementById('rowTemplate'),statusDot=document.getElementById('statusDot'),statusText=document.getElementById('statusText'),refreshText=document.getElementById('refreshText');
const state=new Map();let refreshMs=60000;
function fmt(v){if(!Number.isFinite(v))return '—';if(v>=1e9)return `${(v/1e9).toFixed(2)}B`;if(v>=1e6)return `${(v/1e6).toFixed(2)}M`;if(v>=1e3)return `${(v/1e3).toFixed(1)}K`;return Math.round(v).toLocaleString('en-US')}
function setStatus(c,t){statusDot.className=`status-dot ${c||''}`;statusText.textContent=t}
function save(c){const p=state.get(c.id),v=c.subscribers;state.set(c.id,{serverValue:v,from:p?.serverValue??v,to:v,at:Date.now(),rank:p?.rank??null})}
function shown(id){const s=state.get(id);if(!s)return NaN;const p=Math.min(1,Math.max(0,(Date.now()-s.at)/refreshMs)),e=1-Math.pow(1-p,3);return s.from+(s.to-s.from)*e}
function render(cs){cs=cs.filter(c=>Number.isFinite(c.subscribers));cs.forEach(save);cs.sort((a,b)=>b.subscribers-a.subscribers);const frag=document.createDocumentFragment();cs.forEach((c,i)=>{const s=state.get(c.id),old=s.rank;s.rank=i+1;let r=leaderboard.querySelector(`[data-id="${CSS.escape(c.id)}"]`);if(!r){r=template.content.firstElementChild.cloneNode(true);r.dataset.id=c.id}r.querySelector('.rank').textContent=String(i+1).padStart(2,'0');r.querySelector('.channel-name').textContent=c.name;r.querySelector('.avatar').src=c.avatar||'';r.querySelector('.avatar').alt=`${c.name} avatar`;r.querySelector('.count').textContent=fmt(shown(c.id));const m=r.querySelector('.movement');m.textContent=old==null?'•':old>i+1?'↑':old<i+1?'↓':'•';m.className=`movement ${old>i+1?'up':old<i+1?'down':''}`;r.classList.toggle('top',i<3);frag.appendChild(r)});leaderboard.replaceChildren(frag)}
async function load(){try{const key=localStorage.getItem('yt_tracker_api_key');if(!key)throw Error('Open config.html and enter your YouTube API key.');const list=await fetch('data/channels.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('Channel data unavailable');return r.json()});const ids=list.map(x=>x.id).join(',');if(!ids)throw Error('No channel IDs configured.');const url='https://www.googleapis.com/youtube/v3/channels?part=snippet,statistics&id='+encodeURIComponent(ids)+'&key='+encodeURIComponent(key);const r=await fetch(url,{cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error?.message||'YouTube API request failed');const map=new Map((d.items||[]).map(x=>[x.id,x]));const rows=list.map(c=>{const x=map.get(c.id);return x?{id:x.id,name:x.snippet?.title||c.name,avatar:x.snippet?.thumbnails?.high?.url||x.snippet?.thumbnails?.default?.url,subscribers:x.statistics?.hiddenSubscriberCount?null:Number(x.statistics?.subscriberCount||0)}:null}).filter(Boolean);render(rows);setStatus('online','LIVE');refreshText.textContent=`Updated ${new Date().toLocaleTimeString()}`}catch(e){setStatus('error','SETUP NEEDED');refreshText.textContent=e.message}}
function tick(){state.forEach((_,id)=>{const r=leaderboard.querySelector(`[data-id="${CSS.escape(id)}"]`);if(r)r.querySelector('.count').textContent=fmt(shown(id))});requestAnimationFrame(tick)}
load();setInterval(load,60000);tick();
